export const SELECTED_LEVEL_DATA_REQUEST = 'SELECTED_LEVEL_DATA_REQUEST';
export const SELECTED_LEVEL_DATA_RECEIVED = 'SELECTED_LEVEL_DATA_RECEIVED';
export const MAIN_LEVEL_DATA_REQUEST = 'MAIN_LEVEL_DATA_REQUEST';
export const MAIN_LEVEL_DATA_RECEIVED = 'MAIN_LEVEL_DATA_REQUEST';